### ISSUE TITLE
Problem sending

### ISSUE THREAD

**Issue by Aybilici** [funador/react-confirm-email#2]
Hello @funador, 
There were very few problems. There is an error to send. 

Still uploading while sending. so it doesn't work;
![image](https://user-images.githubusercontent.com/32899796/84032420-fd225000-a99f-11ea-941a-ec9b6e91fc87.png)

Server problem:
![image](https://user-images.githubusercontent.com/32899796/84032168-956c0500-a99f-11ea-9e97-a3c46d91e0ff.png)

mongo:
![image](https://user-images.githubusercontent.com/32899796/84032206-a4eb4e00-a99f-11ea-935c-a78ba993baf1.png)

Thanks!

**Comment by Aybilici** [comment]
Server problem;
Error: Missing credentials for "PLAIN"
    at SMTPConnection._formatError (D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-connection\index.js:675:19)
    at SMTPConnection.login (D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-connection\index.js:432:38)
    at D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-transport\index.js:270:32
    at SMTPConnection.<anonymous> (D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-connection\index.js:188:17)
    at Object.onceWrapper (events.js:427:28)
    at SMTPConnection.emit (events.js:321:20)
    at SMTPConnection._actionEHLO (D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-connection\index.js:1203:14)
    at SMTPConnection._processResponse (D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-connection\index.js:834:20)
    at SMTPConnection._onData (D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-connection\index.js:640:14)
    at TLSSocket.<anonymous> (D:\React Çalışmaları\react-confirm-email-master2\server\node_modules\nodemailer\lib\smtp-connection\index.js:592:47)
    at TLSSocket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'EAUTH',
  command: 'API'
}

**Comment by Aybilici** [comment]
Ahh, I'm sorry. I did not add the careless .env file. Now work. you did a good job decoding. Thank you so much. 👍
